{% set name = "mcplot" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcplot-{{ version }}.tar.gz
  sha256: b08673e053aff424dbebe7d1c9518603c3588b99fccc75afddf03b5e57b90ea8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.5
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - pandas

test:
  imports:
    - mcplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/mcplot
  summary: 'mcplot: plotting class, colormaps and helper functions for plotting.'
  dev_url: https://github.com/mcuntz/mcplot
  license: MIT
  license_file: LICENSE
  description: |
    mcplot provides a class that combines methods to easily produce
    publication-ready graphics on light or black background. It
    includes a large number of colormaps collected from different
    sources. There are a number of functions that help to position
    plots, number plot panels, or generally write text on a graph.
  doc_url: https://mcuntz.github.io/mcplot

extra:
  recipe-maintainers:
    - mcuntz
